galaxy_info:
  author: Prashant Bhosale 
  
  description:  The lxca.compliance ansible role facilitates validating compliance rules by Lenovo
          xClarity Adiministrator.
  
  company: Lenovo 

  license: Apache 2.0

  min_ansible_version: 2.3

  # Optionally specify the branch Galaxy will use when accessing the GitHub
  # repo for this role. During role install, if no tags are available,
  # Galaxy will use this branch. During import Galaxy will access files on
  # this branch. If Travis integration is configured, only notifications for this
  # branch will be accepted. Otherwise, in all cases, the repo's default branch
  # (usually master) will be used.
  #github_branch:

  #
  # platforms is a list of platforms, and each platform has a name and a list of versions.
  #
  platforms:
  - name: Fedora
    versions:
    - all
  - name: Ubuntu 
    versions:
    - all

  galaxy_tags:
  - Lenovo
  - system
  - enterprise
  - lxca
  - xClarity 

dependencies: []
