---
# defaults file for lenovo.lxca-config
manage_user: null
manage_password: null
resource_group_name: null
description: null
type: null
solutionVPD: null
members: null
criteria: null
sol_id: null
manifest_path: null
id: null
solutionGroups: null
comp_rule: null
query_solutionGroups: null
targetResources: null
all_rules: null

