---
# defaults file for lenovo.lxca-config
lxca-config_version: "0.1"
uuid: null
id: null
endpoint_ip: null
user: null
password: null
recovery_password: null
jobid: null
update_mode: null
update_action: null
update_server: null
force: null