- block:
  - name: Updating Firmware of all updateable components from LXCA
    pylxca_module:
      login_user: "{{ lxca_user }}"
      login_password: "{{ lxca_password }}"
      auth_url: "{{ lxca_url }}"
      action: "{{ action }}"
      mode: "{{ mode }}"
      uuid_list: "{{ uuid_list }}"
      command_options: update_firmware_all
    register: rslt_job
  - debug:
      var: rslt_job
  - name: Check firmware update job submission
    assert:
      that:
       -  " 'Success' in rslt_job.msg"
  - debug:
      var: rslt_job.result.JobID

  - name: Polling for Status of firmware update  Operation
    pylxca_module:
      command_options: tasks
      login_user: "{{ lxca_user }}"
      login_password: "{{ lxca_password }}"
      auth_url: "{{ lxca_url }}"
      id: "{{ rslt_job.result.JobID }}"
    register: result
    until: result.result.TaskList[0].percentage == 100.0
    retries: 40
    delay: 15

  - debug:
      var: result.result.TaskList[0]

  - name: Check firmware update job completion status
    assert:
      that:
       -  " 'Complete' in result.result.TaskList[0].status"
       -  " 'CompleteWithErrors' not in result.result.TaskList[0].status"

  tags:
    update_all_firmware_withpolicy

