- name: Updating Firmware of all updateable components from LXCA
  pylxca_module:
    login_user: "{{ lxca_user }}"
    login_password: "{{ lxca_password }}"
    auth_url: "{{ lxca_url }}"
    mode: "{{ mode}}"
    action: "{{ action }}"
    uuid_list: "{{ uuid_list }}"
    command_options: update_firmware_all
  register: rslt
  tags:
     update_all_firmware_withpolicy
